package ro.project.enums;

public enum Style {

    ANCIENT, RENAISSANCE, GOTHIC, BAROQUE, CLASSICISM, ROCOCO, NEOCLASSICISM, ROMANTICISM, REALISM, ARTNOUVEAU, IMPRESSIONISM,
    POSTIMPRESSIONISM, SYMBOLISM, EXPRESSIONISM, CUBISM, SURREALISM, MODERNISM, CONTEMPORARY, AVANTGARDE, UNCERTAIN

}