package ro.itschool.enums;

public enum Style {

    RENAISSANCE, GOTHIC, BAROQUE, CLASSICISM, ROCOCO, NEOCLASSICISM, ROMANTICISM, REALISM, ARTNOUVEAU, IMPRESSIONISM,
    POSTIMPRESSIONISM, SYMBOLISM, EXPRESSIONISM, CUBISM, SURREALISM, MODERNISM, CONTEMPORARY,

}
